# One-line installer for the darktable -> IOPaint integration (Windows).
#
#   irm https://raw.githubusercontent.com/masterpiga/darktable-iopaint/main/install.ps1 | iex
#
# Clones this fork, builds it (virtualenv + dependencies + web frontend), wires the
# Lua script into darktable, and optionally pre-downloads the model. Afterwards just
# start darktable - the "IOPaint" panel appears in lighttable and darkroom.
#
# Requires: git, Node.js/npm, and a Python 3.8-3.11 (the 'py' launcher or 'python').
#
# Non-interactive overrides (env vars): IOPAINT_DT_REPO, IOPAINT_DT_INSTALL_DIR,
# IOPAINT_DT_CONFIG_DIR, IOPAINT_DT_PREDOWNLOAD (y/n).

$ErrorActionPreference = "Stop"

function Say($m)  { Write-Host "==> $m" -ForegroundColor Cyan }
function Die($m)  { Write-Host "error: $m" -ForegroundColor Red; exit 1 }
function Need($c) { if (-not (Get-Command $c -ErrorAction SilentlyContinue)) { Die "'$c' is required but not found on PATH." } }
function Ask($msg, $def) {
  $a = Read-Host "$msg [$def]"
  if ([string]::IsNullOrWhiteSpace($a)) { return $def } else { return $a }
}

$RepoUrl = if ($env:IOPAINT_DT_REPO) { $env:IOPAINT_DT_REPO } else { "https://github.com/masterpiga/darktable-iopaint.git" }
$DefaultInstall = Join-Path $env:LOCALAPPDATA "darktable-iopaint"
$DefaultConfig  = Join-Path $env:LOCALAPPDATA "darktable"

Say "darktable-iopaint installer"
Need git
Need npm

$InstallDir = if ($env:IOPAINT_DT_INSTALL_DIR) { $env:IOPAINT_DT_INSTALL_DIR } else { Ask "Install darktable-iopaint to" $DefaultInstall }
$ConfigDir  = if ($env:IOPAINT_DT_CONFIG_DIR)  { $env:IOPAINT_DT_CONFIG_DIR }  else { Ask "darktable config directory" $DefaultConfig }
$Predownload= if ($env:IOPAINT_DT_PREDOWNLOAD) { $env:IOPAINT_DT_PREDOWNLOAD } else { Ask "Pre-download the lama model now? (y/n)" "y" }

# find a supported Python (3.8-3.11)
function Find-Python {
  foreach ($v in @("3.11","3.10","3.9","3.8")) {
    if (Get-Command py -ErrorAction SilentlyContinue) {
      & py "-$v" --version *> $null
      if ($LASTEXITCODE -eq 0) { return @("py", "-$v") }
    }
  }
  if (Get-Command python -ErrorAction SilentlyContinue) {
    $ver = (& python -c "import sys;print('%d.%d'%sys.version_info[:2])")
    if ($ver -in @("3.8","3.9","3.10","3.11")) { return @("python") }
  }
  Die "no supported Python found (need 3.8-3.11). Install Python 3.11 from python.org and retry."
}

# 1. clone or update
if (Test-Path (Join-Path $InstallDir ".git")) {
  Say "Updating existing checkout in $InstallDir"
  git -C $InstallDir pull --ff-only
} else {
  Say "Cloning $RepoUrl -> $InstallDir"
  New-Item -ItemType Directory -Force -Path (Split-Path $InstallDir) | Out-Null
  git clone $RepoUrl $InstallDir
}

# 2. build (setup.sh is bash-only, so replicate it here)
$py = Find-Python
$VenvDir = Join-Path $InstallDir ".venv"
$VenvPy  = Join-Path $VenvDir "Scripts\python.exe"
if (-not (Test-Path $VenvPy)) {
  Say "Creating virtualenv"
  & $py[0] $py[1..($py.Count-1)] -m venv $VenvDir
}
Say "Installing IOPaint (this fork) and dependencies…"
& $VenvPy -m pip install --upgrade pip | Out-Null
& $VenvPy -m pip install -e $InstallDir

Say "Building web frontend…"
Push-Location (Join-Path $InstallDir "web_app")
if (-not (Test-Path "node_modules")) { npm install }
npm run build
Pop-Location
$webDst = Join-Path $InstallDir "iopaint\web_app"
if (Test-Path $webDst) { Remove-Item -Recurse -Force $webDst }
Copy-Item -Recurse (Join-Path $InstallDir "web_app\dist") $webDst

# 3. install a loader into darktable's lua scripts dir so the script appears in the
#    "lua scripts" (script manager) panel. The shim loads the real script from the
#    checkout via dofile, so it auto-detects its repo and tracks git updates.
$ContribDir = Join-Path $ConfigDir "lua\contrib"
New-Item -ItemType Directory -Force -Path $ContribDir | Out-Null
$Shim = Join-Path $ContribDir "iopaint.lua"
$luaPath = ($InstallDir -replace '\\','/')   # lua paths use forward slashes
@"
-- darktable-iopaint loader (generated by install.ps1)
-- Loads the script from the source checkout so it auto-detects its location
-- and picks up git updates. Enable/disable it from the lua scripts panel.
return dofile("$luaPath/darktable/iopaint.lua")
"@ | Set-Content -Path $Shim -Encoding UTF8
Say "Installed script-manager loader: $Shim"

# 4. optional model pre-download
if ($Predownload -match '^[Yy]') {
  Say "Pre-downloading the lama model…"
  try { & $VenvPy -m iopaint download --model lama } catch { Write-Host "warning: model pre-download failed; it will download on first use" -ForegroundColor Yellow }
} else {
  Say "Skipping model pre-download (it downloads automatically on first use)"
}

Say "Done!"
Write-Host ""
Write-Host "  Next, in darktable:"
Write-Host "    1. Open the 'lua scripts' panel, find 'iopaint' under 'contrib', and enable it."
Write-Host "    2. The 'IOPaint' panel then appears in lighttable (right) and darkroom (left)."
Write-Host "    3. Select images (or open one in darkroom) and click 'send selection to IOPaint'."
Write-Host ""
Write-Host "  Installed at : $InstallDir"
Write-Host "  darktable cfg: $ConfigDir"
